spring.application.name=gateway

server.port=8080

##rutas
spring.cloud.gateway.routes[0].id=apiService
spring.cloud.gateway.routes[0].uri=http://localhost:8081
##rutas que contenga /api/** se redirigen
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/**
##spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[1].id=analyticsService
spring.cloud.gateway.routes[1].uri=http://localhost:8082
##rutas que contenga /analytics/** se redirigen
spring.cloud.gateway.routes[1].predicates[0]=Path=/analytics/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1

## Logging
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.root=INFO